-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS admin;

CREATE TABLE users (
  userID INTEGER PRIMARY KEY AUTOINCREMENT,
  firstName TEXT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  driverID INTEGER FOREIGN KEY,
  teamID INTEGER FOREIGN KEY,
  newsletter BOOLEAN,
  verified BOOLEAN
);

CREATE TABLE admin (
  adminID INTEGER PRIMARY KEY AUTOINCREMENT,
  userID INTEGER FOREIGN KEY,
  permissions INTEGER NOT NULL,
)